import XCTest
@testable import SinchChatSDK

/// Tests covering the outgoing-message dedup logic introduced to fix the
/// `.sending` + `.sent` duplication bug.
final class StartViewModelSendTests: XCTestCase {

    private var viewModel: DefaultStartViewModel!
    private var dataSource: ReplayingMessageDataSource!
    private var delegate: RecordingDelegate!
    private let pushNotificationHandler: PushNotificationHandler = PushNotificationHandlerStub()

    override func setUp() {
        super.setUp()
        dataSource = ReplayingMessageDataSource()
        viewModel = DefaultStartViewModel(messageDataSource: dataSource,
                                         notificationPermission: pushNotificationHandler)
        delegate = RecordingDelegate()
        viewModel.delegate = delegate
        // Default to connected.
        viewModel.setInternetConnectionState(.isOn)
    }

    override func tearDown() {
        viewModel = nil
        dataSource = nil
        delegate = nil
        super.tearDown()
    }

    func test_sendTextMessage_insertsOptimisticBeforeNetworkResponse() {
        // Arrange
        let tempIdExpectation = expectation(description: "received optimistic message")
        var receivedTempId: String?
        delegate.onDidReceiveMessages = { messages in
            guard messages.count > 0, let first = messages.first(where: { $0.status == .sending }) else { return }
            receivedTempId = first.entryId
            tempIdExpectation.fulfill()
        }

        dataSource.sendMessageServerEntryId = "server-1"
        dataSource.sendMessageCompletion = .success("server-1")

        // Act
        viewModel.sendMessage(.text("Hello")) { _ in }

        wait(for: [tempIdExpectation], timeout: 1.0)

        // Assert
        XCTAssertNotNil(receivedTempId, "Optimistic message should be inserted before the network completes")
        XCTAssertTrue(receivedTempId?.hasPrefix("tmp-") == true, "Optimistic entryId should be a temp id, got \(receivedTempId ?? "nil")")
        XCTAssertEqual(dataSource.capturedMessageTypes.count, 1, "sendMessage should still be called on the data source")
    }

    func test_sendTwoMessages_useDistinctTempIds() {
        // Arrange
        var tempIds: [String] = []
        delegate.onDidReceiveMessages = { messages in
            for message in messages where message.status == .sending {
                tempIds.append(message.entryId)
            }
        }
        dataSource.sendMessageServerEntryId = "server-1"
        dataSource.sendMessageCompletion = .success("server-1")

        // Act
        viewModel.sendMessage(.text("First")) { _ in }
        viewModel.sendMessage(.text("Second")) { _ in }

        // Assert
        XCTAssertEqual(tempIds.count, 2)
        XCTAssertEqual(Set(tempIds).count, 2, "Each send should get a distinct temp id, got \(tempIds)")
    }

    func test_serverEcho_swapsOptimisticInPlace_noDuplicate() {
        // Arrange: capture the tempId that gets generated by the optimistic insert.
        var capturedTempId: String?
        delegate.onDidReceiveMessages = { [weak self] messages in
            guard let self else { return }
            for message in messages where message.status == .sending {
                capturedTempId = message.entryId
            }
            self.recordInserted(messages)
        }
        dataSource.sendMessageServerEntryId = "server-1"
        dataSource.sendMessageCompletion = .success("server-1")

        // Act 1: send a message. This inserts the optimistic and registers the server-id mapping.
        viewModel.sendMessage(.text("Hello")) { _ in }

        // The server echoes the same message back with the server-assigned entryId.
        let echo = Message(entryId: "server-1",
                           owner: .outgoing,
                           body: MessageText(text: "Hello", sendDate: 1637058195))
        let resolveExpectation = expectation(description: "view controller notified of resolve")
        delegate.onDidResolveOutgoingMessage = { tempId, resolved in
            XCTAssertEqual(tempId, capturedTempId, "Swap should reference the original temp id")
            XCTAssertEqual(resolved.entryId, "server-1", "Resolved message should carry the server entryId")
            XCTAssertEqual(resolved.status, .sent, "Resolved message should have status .sent")
            resolveExpectation.fulfill()
        }

        // Reset the captured echoes so we can distinguish the optimistic from
        // the resolve.
        delegate.reset()

        // Act 2: simulate the server echo coming through the subscription.
        viewModel.subscribeForMessages { _ in }
        dataSource.deliverSubscriptionEcho(echo)

        wait(for: [resolveExpectation], timeout: 1.0)

        // The view model must NOT insert a second message via the standard
        // `didReceiveMessages` path; the only notification should be the
        // dedicated `didResolveOutgoingMessage` call.
        XCTAssertTrue(delegate.didReceiveMessagesCallsAfterReset.isEmpty,
                      "didReceiveMessages should not be invoked for an outgoing echo that resolves an optimistic insert")
    }

    func test_retryAfterFailure_reusesTempId() {
        // Arrange: first send fails, second send succeeds.
        var tempIds: [String] = []
        delegate.onDidReceiveMessages = { messages in
            for message in messages where message.status == .sending {
                tempIds.append(message.entryId)
            }
        }

        let failedExpectation = expectation(description: "failure marks optimistic as notSent")
        delegate.onDidFailToSend = { tempId, status in
            XCTAssertEqual(status, .notSent)
            XCTAssertEqual(tempId, tempIds.first)
            failedExpectation.fulfill()
        }

        dataSource.sendMessageCompletion = .failure(.unknown(NSError(domain: "test", code: 1)))

        viewModel.sendMessage(.text("Hello")) { _ in }
        wait(for: [failedExpectation], timeout: 1.0)

        let retryExpectation = expectation(description: "retry succeeds")
        dataSource.sendMessageServerEntryId = "server-2"
        dataSource.sendMessageCompletion = .success("server-2")
        delegate.onDidFailToSend = { _, _ in
            XCTFail("Should not be called for successful retry")
        }
        delegate.onDidResolveOutgoingMessage = { _, _ in
            // Not strictly required to be called for a non-echo retry, but
            // acceptable. The important invariant is the temp id is reused.
        }
        delegate.reset()
        viewModel.sendMessage(.text("Hello")) { _ in
            retryExpectation.fulfill()
        }

        wait(for: [retryExpectation], timeout: 1.0)
        XCTAssertEqual(tempIds.count, 2, "Retry should generate a fresh optimistic insert")
        XCTAssertEqual(tempIds[0], tempIds[1],
                       "Failed optimistic should be reused for the retry; got \(tempIds)")
    }

    func test_onDisappear_clearsMappings() {
        // Arrange: a successful send populates the serverEntryId → tempId map.
        let successExpectation = expectation(description: "sendMessage success")
        dataSource.sendMessageServerEntryId = "server-3"
        dataSource.sendMessageCompletion = .success("server-3")
        viewModel.sendMessage(.text("Hello")) { _ in
            successExpectation.fulfill()
        }
        wait(for: [successExpectation], timeout: 1.0)

        // Act
        viewModel.onDisappear()

        // After disappear we expect that an echo with the same server id
        // does NOT trigger a resolve. Send the echo and verify no
        // didResolveOutgoingMessage call.
        delegate.onDidResolveOutgoingMessage = { _, _ in
            XCTFail("Resolve should not fire after the chat session is reset")
        }
        let echo = Message(entryId: "server-3",
                           owner: .outgoing,
                           body: MessageText(text: "Hello", sendDate: 1637058195))
        viewModel.subscribeForMessages { _ in }
        dataSource.deliverSubscriptionEcho(echo)
        _ = XCTWaiter.wait(for: [expectation(description: "wait")], timeout: 0.5)
    }
}

// MARK: - Helpers

private final class RecordingDelegate: StartViewModelDelegate {

    var onDidReceiveMessages: (([Message]) -> Void)?
    var onDidResolveOutgoingMessage: ((String, Message) -> Void)?
    var onDidFailToSend: ((String, MessageStatus) -> Void)?
    var onDidReceiveHistoryFirstMessages: (([Message]) -> Void)?
    var onDidReceiveHistoryMessages: (([Message]) -> Void)?

    private(set) var didReceiveMessagesCallsAfterReset: [[Message]] = []

    func recordInserted(_ messages: [Message]) {
        didReceiveMessagesCallsAfterReset.append(messages)
    }

    func reset() {
        didReceiveMessagesCallsAfterReset.removeAll()
    }

    func didReceiveMessages(_ message: [Message]) {
        onDidReceiveMessages?(message)
        recordInserted(message)
    }

    func didResolveOutgoingMessage(tempId: String, resolved: Message) {
        onDidResolveOutgoingMessage?(tempId, resolved)
    }

    func didFailToSend(tempId: String, status: MessageStatus) {
        onDidFailToSend?(tempId, status)
    }

    func didReceiveHistoryFirstMessages(_ messages: [Message]) {
        onDidReceiveHistoryFirstMessages?(messages)
    }

    func didReceiveHistoryMessages(_ messages: [Message]) {
        onDidReceiveHistoryMessages?(messages)
    }

    func errorLoadingMoreHistory(error: MessageDataSourceError) {}
    func errorSendingMessage(error: MessageDataSourceError) {}
    func didChangeInternetState(_ state: InternetConnectionState) {}
    func setVisibleRefreshActivityIndicator(_ isVisible: Bool) {}
    func setVisibleTypingIndicator(_ isVisible: Bool, animated: Bool) {}
}

private final class ReplayingMessageDataSource: MessageDataSource, @unchecked Sendable {
    var topicModel: TopicModel?
    var metadata: SinchMetadataArray = []
    var shouldInitializeConversation = false

    weak var delegate: MessageDataSourceDelegate?

    var sendMessageServerEntryId: String = "server-default"
    var sendMessageCompletion: Result<String, MessageDataSourceError> = .success("server-default")
    private(set) var capturedMessageTypes: [MessageType] = []
    private(set) var sendMessageCallCount = 0

    private var pendingSubscriptionCompletion: ((Result<Message, MessageDataSourceError>) -> Void)?

    // MARK: - Async stubs (unused in these tests; required by protocol)
    func uploadMedia(_ media: MediaType) async throws -> String { "" }
    func uploadMediaViaStream(_ media: MediaType) async throws -> String { "" }
    func sendMessage(_ message: MessageType) async throws -> String { "" }
    func sendEvent(_ event: EventType) async throws {}
    func subscribeForMessages() -> AsyncThrowingStream<Message, Error> {
        AsyncThrowingStream { $0.finish() }
    }
    func getMessageHistory() async throws -> [Message] { [] }
    func sendConversationMetadata(_ metadata: SinchMetadataArray) throws {}

    func isSubscribed() -> Bool { true }
    func isFirstPage() -> Bool { true }
    func cancelCalls() {}
    func cancelSubscription() {}
    func closeChannel() {}
    func startChannel() {}

    // MARK: - Completion-handler entry points used by these tests
    func sendMessage(_ message: MessageType,
                     completion: @escaping @Sendable (Result<String, MessageDataSourceError>) -> Void) {
        capturedMessageTypes.append(message)
        sendMessageCallCount += 1
        completion(sendMessageCompletion)
    }

    func sendEvent(_ event: EventType,
                   completion: @escaping @Sendable (Result<Void, MessageDataSourceError>) -> Void) {
        completion(.success(()))
    }

    func subscribeForMessages(completion: @escaping @Sendable (Result<Message, MessageDataSourceError>) -> Void) {
        pendingSubscriptionCompletion = completion
    }

    func getMessageHistory(completion: @escaping @Sendable (Result<[Message], MessageDataSourceError>) -> Void) {
        completion(.success([]))
    }

    func sendConversationMetadata(_ metadata: SinchMetadataArray) -> Result<Void, MessageDataSourceError> {
        .success(())
    }

    func uploadMedia(_ media: MediaType,
                     completion: @escaping @Sendable (Result<String, MessageDataSourceError>) -> Void) {
        completion(.success(""))
    }

    func uploadMediaViaStream(_ media: MediaType,
                              completion: @escaping @Sendable (Result<String, MessageDataSourceError>) -> Void) {
        completion(.success(""))
    }

    /// Test helper: deliver a single subscription echo to the most recent
    /// subscriber registered via `subscribeForMessages(completion:)`.
    func deliverSubscriptionEcho(_ message: Message) {
        pendingSubscriptionCompletion?(.success(message))
        pendingSubscriptionCompletion = nil
    }
}